import { cn } from "@/lib/utils"
import {
  Armchair,
  ArrowLeft,
  ArrowRight,
  BadgeCheck,
  Bell,
  Bus,
  Calendar,
  CalendarCheck,
  CalendarDays,
  Car,
  CarFront,
  CarTaxiFront,
  Check,
  CheckCheck,
  ChevronRight,
  CircleCheck,
  CirclePlus,
  CircleX,
  Clock,
  CreditCard,
  ExternalLink,
  Eye,
  EyeOff,
  Flag,
  Globe,
  Handshake,
  Headset,
  LayoutDashboard,
  Leaf,
  LogOut,
  Mail,
  MapPin,
  Menu,
  MessageCircle,
  MessagesSquare,
  Navigation,
  Pencil,
  Phone,
  PartyPopper,
  Route,
  Save,
  Search,
  Send,
  Share,
  Shield,
  ShieldAlert,
  ShieldCheck,
  SlidersHorizontal,
  Smartphone,
  Star,
  User,
  UserCheck,
  UserPlus,
  Venus,
  Wind,
} from "lucide-react"

const iconMap = {
  add_circle: CirclePlus,
  air: Wind,
  arrow_back: ArrowLeft,
  arrow_forward: ArrowRight,
  calendar_month: CalendarDays,
  calendar_today: Calendar,
  call: Phone,
  cancel: CircleX,
  celebration: PartyPopper,
  chat: MessagesSquare,
  chat_bubble: MessageCircle,
  check: Check,
  check_circle: CircleCheck,
  chevron_right: ChevronRight,
  commute: Bus,
  dashboard: LayoutDashboard,
  directions_car: Car,
  done_all: CheckCheck,
  drive_eta: CarFront,
  east: ArrowRight,
  eco: Leaf,
  edit: Pencil,
  electric_car: CarTaxiFront,
  event_available: CalendarCheck,
  event_seat: Armchair,
  female: Venus,
  flag: Flag,
  gpp_good: ShieldCheck,
  handshake: Handshake,
  how_to_reg: UserCheck,
  language: Globe,
  location_on: MapPin,
  logout: LogOut,
  mail: Mail,
  manage_search: SlidersHorizontal,
  menu: Menu,
  notifications: Bell,
  near_me: Navigation,
  open_in_new: ExternalLink,
  payments: CreditCard,
  person: User,
  person_add: UserPlus,
  phone: Phone,
  privacy_tip: ShieldAlert,
  route: Route,
  save: Save,
  schedule: Clock,
  search: Search,
  security: Shield,
  send: Send,
  share: Share,
  smartphone: Smartphone,
  star: Star,
  support_agent: Headset,
  trending_flat: ArrowRight,
  verified: BadgeCheck,
  visibility: Eye,
  visibility_off: EyeOff,
}

function Icon({
  name,
  size = 20,
  filled = false,
  className,
  ...props
}) {
  const Cmp = iconMap[name]
  if (!Cmp) {
    return null
  }

  return (
    <Cmp
      name={name}
      size={size}
      aria-hidden="true"
      data-slot="icon"
      className={cn("shrink-0", filled && "fill-current", className)}
      {...props} />
  );
}

export { Icon, iconMap }
